const specialtyPages = [
  {id:"urologic-oncology",title:"Urologic Oncology",tagline:"Michigan's most comprehensive cancer program — from screening to survivorship.",
   icon:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10z"/><path d="M12 8v8M8 12h8"/></svg>',
   overview:"The Division of Urologic Oncology at Michigan Medicine is one of the nation's leading programs for the diagnosis and treatment of cancers of the prostate, bladder, kidney, testis, and penis. Our multidisciplinary tumor board — comprising urologists, medical oncologists, radiation oncologists, and pathologists — reviews every patient's case to recommend a personalized treatment plan. Led by Dr. Ganesh Palapattu (Department Chair), our surgeons perform over 450 robotic procedures annually, and our faculty lead federally funded clinical trials through the NCI, Department of Defense, and Prostate Cancer Foundation.",
   highlights:["Weekly multidisciplinary tumor board review for every cancer patient","Over 450 robotic surgeries performed annually","NCI, DoD, and Prostate Cancer Foundation–funded clinical trials","Liquid biopsy and genomic-guided precision oncology programs","Intracorporeal urinary diversion for bladder cancer — minimizing recovery time","MUSIC quality collaborative — Michigan's statewide urology improvement initiative"],
   conditions:["Prostate Cancer","Bladder Cancer","Kidney Cancer","Testicular Cancer","Penile Cancer","Ureteral Cancer","Adrenal Tumors"],
   research:"Our translational research program spans liquid biopsy for prostate cancer (Dr. Morgan), circulating tumor cell genomics (Dr. Salami), focal therapy innovation (Dr. Wood), health services research examining cost and quality of cancer care (Drs. Miller, Hollenbeck, Borza, Herrel), and clinical trial design including novel bladder cancer therapies and active surveillance optimization (Drs. Kaffenberger, Singhal, Stensland).",
   facultyIds:["borza","faraj","hafez","herrel","hollenbeck","kaffenberger","miller","montgomery","morgan","palapattu","salami","semerjian","singhal","srivastava","stensland","wood"],
   links:[{title:"Rogel Cancer Center – Prostate Cancer",url:"https://www.rogelcancercenter.org/prostate-cancer/resources"},{title:"Rogel Cancer Center – Bladder Cancer",url:"https://www.rogelcancercenter.org/bladder-cancer"},{title:"MUSIC Quality Collaborative",url:"https://musicurology.com/"},{title:"Prostate Cancer Research",url:"https://medicine.umich.edu/dept/urology/research/divisional-research/clinical-divisions/urologic-oncology/prostate-cancer-research"}]},

  {id:"mens-health",title:"Men's Health & Reconstruction",tagline:"Expert care for BPH, male infertility, sexual health, and reconstructive urology.",
   icon:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 12h-4l-3 9L9 3l-3 9H2"/></svg>',
   overview:"The Division of Men's Health & Reconstruction provides comprehensive care for benign prostate conditions, male reproductive health, sexual dysfunction, and complex genitourinary reconstruction. Our team includes fellowship-trained surgeons, advanced practice providers, and a nationally recognized nurse practitioner specializing in men's health. From Rezūm water vapor therapy for BPH to microsurgical vasectomy reversal and gender-affirming surgery, we offer the full spectrum of care.",
   highlights:["Boston Scientific AMS 700 Center of Excellence for penile prosthetics","Advanced BPH therapies including Rezūm, bipolar TURP, and HoLEP","Microsurgical vasectomy reversal and male fertility preservation","Gender-affirming surgical program","Telemedicine follow-up options for appropriate consultations","Opioid-free vasectomy recovery protocols"],
   conditions:["Enlarged Prostate (BPH)","Male Infertility","Erectile Dysfunction","Vasectomy & Reversal","Peyronie's Disease","Urethral Stricture","Low Testosterone","Gender-Affirming Surgery","Penile Prosthetics","Chronic Scrotal Pain"],
   research:"Research in this division spans health services research examining insurance coverage for fertility care and value-based BPH treatment (Dr. Dupree), telemedicine innovation and virtual care delivery (Dr. Ellimoottil), tissue engineering and advanced prosthetic technologies (Dr. Malaeb), surgical ergonomics and surgeon well-being (Dr. Chrouser), and workforce equity in reproductive urology (Dr. Nam).",
   facultyIds:["blair","chrouser","dupree","ellimoottil","hadjmoussa","malaeb","nam","ohl","quallich","wei"],
   links:[{title:"BPH – Michigan Medicine",url:"https://www.uofmhealth.org/our-care/specialties-services/benign-prostatic-hyperplasia"},{title:"Male Infertility – Michigan Medicine",url:"https://www.uofmhealth.org/our-care/specialties-services/male-infertility"},{title:"Erectile Dysfunction – Michigan Medicine",url:"https://www.uofmhealth.org/our-care/specialties-services/erectile-dysfunction"}]},

  {id:"neurourology",title:"Neurourology & Pelvic Reconstruction",tagline:"Specialized care for complex voiding dysfunction, neurogenic bladder, and pelvic floor disorders.",
   icon:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/></svg>',
   overview:"Led by Dr. John Stoffel, the Division of Neurourology and Pelvic Reconstructive Surgery treats patients with complex voiding dysfunction resulting from neurological conditions (spinal cord injury, multiple sclerosis, spina bifida), pelvic floor disorders, urinary incontinence, and complications from prior urologic surgery. Our team is certified in Female Pelvic Medicine and Reconstructive Surgery (FPMRS) and leads multi-institutional research through the Neurogenic Bladder Research Group.",
   highlights:["Division Chief: Dr. John Stoffel — 110+ published papers, textbook editor","FPMRS board-certified surgeons","Multi-institutional Neurogenic Bladder Research Group leadership","Complex abdominal reconstructive surgery including colon conduit diversion","Collaborative care with PM&R, neurology, and gynecology","Advanced urodynamic testing and diagnostics"],
   conditions:["Neurogenic Bladder","Urinary Incontinence (Male & Female)","Overactive Bladder","Spinal Cord Injury Urology","Multiple Sclerosis–Related Bladder Dysfunction","Pelvic Organ Prolapse","Urinary Fistula","Urethral Diverticulum"],
   research:"Division research focuses on understanding bladder phenotypes after spinal cord injury using machine learning, patient-reported outcomes for neurogenic bladder, optimizing bladder management strategies to reduce autonomic dysreflexia, and studying patient experiences of stigma associated with overactive bladder. The division has received federal and industry-sponsored grants supporting these programs.",
   facultyIds:["barboglio-romo","cameron","clemens","goh","gupta","ippolito","kielb","stoffel"],
   links:[{title:"Neurourology Division – Michigan Medicine",url:"https://medicine.umich.edu/dept/urology/divisions/clinical-divisions/neurourology-pelvic-reconstructive-surgery"}]},

  {id:"endourology",title:"Endourology",tagline:"Minimally invasive treatment for kidney stones and upper tract conditions.",
   icon:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg>',
   overview:"Michigan Medicine's Endourology division provides advanced treatment for kidney stones (urolithiasis) and upper urinary tract conditions using minimally invasive technology. Our team participates in MUSIC's ROCKS (Reducing Operative Complications from Kidney Stones) quality collaborative, ensuring every patient benefits from evidence-based, data-driven care protocols. Treatment options include shock wave lithotripsy (SWL), ureteroscopy (URS), and percutaneous nephrolithotomy (PCNL), along with comprehensive metabolic prevention programs.",
   highlights:["Participation in MUSIC ROCKS kidney stone quality collaborative","Full range of minimally invasive stone treatment: SWL, URS, PCNL","Metabolic stone prevention programs to reduce recurrence","Advanced imaging protocols optimized through quality initiatives","Pain management optimization pathways for post-procedure care","Shared decision aids to help patients choose the right procedure"],
   conditions:["Kidney Stones","Ureteral Stones","Ureteral Stricture","Upper Tract Urothelial Carcinoma","UPJ Obstruction"],
   research:"The ROCKS collaborative drives research on optimizing imaging after kidney stone surgery, safely managing pain after ureteroscopy, developing stent omission criteria, and creating shared decision aids for patients choosing between SWL and URS.",
   facultyIds:["ambani","dauw","ghani","hadjmoussa","krishna","roberts","sui","uy"],
   links:[{title:"MUSIC ROCKS – Kidney Stone Quality",url:"https://musicurology.com/programs/rocks/"},{title:"MUSIC Patient Materials – Kidney Stones",url:"https://musicurology.com/resources/patient-educational-materials/"}]},

  {id:"community-urology",title:"Community Urology",tagline:"Bringing Michigan Medicine expertise to communities across the state.",
   icon:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 2a7 7 0 0 0-7 7c0 5 7 13 7 13s7-8 7-13a7 7 0 0 0-7-7z"/><circle cx="12" cy="9" r="2.5"/></svg>',
   overview:"Community Urology extends the full spectrum of Michigan Medicine urological expertise to patients across Michigan, eliminating the need to travel to Ann Arbor for routine and many specialized services. Our community urologists practice at satellite locations including Brighton, Chelsea, Canton, Livonia, Northville, and beyond — providing the same evidence-based, quality-driven care found at our main campus.",
   highlights:["Satellite clinics in Brighton, Chelsea, Canton, Livonia, Northville, and more","Same quality standards and clinical protocols as Ann Arbor campus","Access to Michigan Medicine's multidisciplinary resources when needed","Convenient scheduling with shorter wait times at community sites","Seamless referral to Ann Arbor specialists for complex cases","Telehealth options for eligible follow-up appointments"],
   conditions:["General Urology","BPH","Kidney Stones","Elevated PSA","Urinary Tract Infections","Hematuria Evaluation","Erectile Dysfunction","Vasectomy"],
   research:"Community urologists contribute to MUSIC quality collaborative data, ensuring statewide practice patterns reflect the latest evidence and best outcomes.",
   facultyIds:["claflin","eames","ellimoottil","faris","fox","goldman","jphelps","king","ohl","pugashetti","quallich","stork","walker","wei"],
   links:[{title:"Find a Location",url:"#locations"}]},

  {id:"pediatric-urology",title:"Pediatric Urology",tagline:"Fellowship-trained specialists providing compassionate care for children.",
   icon:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"/></svg>',
   overview:"Michigan Medicine's Pediatric Urology division is ranked among the best in Michigan for children's urological care. Our fellowship-trained pediatric urologists specialize in treating congenital and acquired urological conditions in infants, children, and adolescents. We work closely with pediatric nephrologists, neonatologists, and other specialists to provide coordinated, family-centered care.",
   highlights:["Ranked best in Michigan for pediatric urology","Fellowship-trained pediatric urologists","Coordinated care with C.S. Mott Children's Hospital specialists","Family-centered approach with child life specialists","Minimally invasive and robotic surgical options for children","Transition-of-care programs for adolescents moving to adult urology"],
   conditions:["Vesicoureteral Reflux","Hypospadias","Undescended Testes","Ureteropelvic Junction Obstruction","Posterior Urethral Valves","Pediatric Kidney Stones","Bladder Exstrophy","Neurogenic Bladder in Children"],
   research:"Pediatric research at Michigan includes participation in multi-institutional studies examining outcomes for common pediatric urological conditions and quality improvement initiatives within C.S. Mott Children's Hospital.",
   facultyIds:["bloom","kraft","streur","wan"],
   links:[{title:"C.S. Mott Children's Hospital – Urology",url:"https://www.mottchildren.org/conditions-treatments/ped-urology"}]}
];

const locationPages = [
  {id:"taubman",title:"Taubman Center – Ann Arbor",tagline:"Our flagship clinical campus and home to the full department.",
   address:"1500 E. Medical Center Dr., Floor 3, Reception A, Ann Arbor, MI 48109",
   phone:"(734) 936-7030",
   hours:"Monday–Friday, 8:00 AM – 5:00 PM",
   overview:"The Taubman Center is the primary clinical home of the Department of Urology at Michigan Medicine. Located on Floor 3, Reception A, it houses the full spectrum of our clinical divisions — from urologic oncology and men's health to neurourology and endourology. Patients benefit from same-day access to advanced diagnostics including urodynamics, MRI-fusion biopsy, and in-clinic ultrasound. The Taubman Center is directly connected to the University Hospital surgical suites, Rogel Cancer Center, and all Michigan Medicine inpatient facilities.",
   services:["All six clinical divisions represented","Advanced diagnostics: urodynamics, cystoscopy, MRI-fusion biopsy","Robotic surgery suites (University Hospital)","Direct connection to Rogel Cancer Center","On-site lab work and imaging","Clinical trial enrollment and research visits"],
   directions:"From US-23, take Exit 37B (Plymouth Road). Turn right on Huron Parkway, then left on E. Medical Center Drive. Patient parking is available in Structure P1 (Taubman Center Patient Parking). Valet service is available at the main entrance.",
   mapUrl:"https://maps.google.com/?q=1500+E+Medical+Center+Dr,+Ann+Arbor,+MI+48109"},
  {id:"brighton",title:"Brighton Center for Specialty Care",tagline:"Convenient Livingston County access to expert urological care.",
   address:"7500 Challis Rd., Brighton, MI 48116",
   phone:"(734) 936-7030",
   hours:"Select days — call for current schedule",
   overview:"The Brighton Center for Specialty Care brings Michigan Medicine urology expertise to Livingston County. Select providers hold regular clinic hours here, offering evaluation and management of common urological conditions without requiring a trip to Ann Arbor. The facility includes exam rooms, consultation suites, and on-site basic diagnostics.",
   services:["BPH evaluation and management","Prostate cancer screening and follow-up","Kidney stone evaluation","General urology consultations","Post-surgical follow-up visits"],
   directions:"Located on Challis Road, just off I-96 at Exit 145 (Spencer Road). The center is in the Michigan Medicine Brighton complex near the Brighton Health Center.",
   mapUrl:"https://maps.google.com/?q=7500+Challis+Rd,+Brighton,+MI+48116"},
  {id:"chelsea",title:"Chelsea Health Center",tagline:"Full-service urology care in western Washtenaw County.",
   address:"14700 E. Old US-12, Suite 2100, Chelsea, MI 48118",
   phone:"(734) 936-7030",
   hours:"Select days — call for current schedule",
   overview:"The Chelsea Health Center extends Michigan Medicine's urological care to patients in western Washtenaw County and surrounding communities. Providers from both the oncology and men's health divisions see patients here on a regular schedule, offering continuity of care close to home.",
   services:["Urologic oncology follow-up","Men's health consultations","BPH management","General urology","Pre- and post-operative visits"],
   directions:"The Chelsea Health Center is located on E. Old US-12 (also known as Jackson Road), about 1 mile east of downtown Chelsea. Free parking is available on site.",
   mapUrl:"https://maps.google.com/?q=14700+E+Old+US+12,+Chelsea,+MI+48118"},
  {id:"northville",title:"Northville Health Center",tagline:"Michigan Medicine specialty care in western Wayne County.",
   address:"39901 Traditions Dr., Northville, MI 48168",
   phone:"(734) 936-7030",
   hours:"Select days — call for current schedule",
   overview:"Michigan Medicine's 100,000 square-foot Northville Health Center is located approximately 30 minutes from the main Ann Arbor campus, at the intersection of West Seven Mile Road and Haggerty Road. The urology clinic here offers evaluation and treatment for men's health conditions, pelvic floor disorders, and general urology. Providers from both the Men's Health & Reconstruction and Neurourology divisions see patients at this location.",
   services:["Men's health consultations","Erectile dysfunction and sexual health","BPH evaluation and management","Pelvic floor disorder assessment","General urology","Post-surgical follow-up visits"],
   directions:"From I-275, take Exit 167 (Eight Mile Road/Haggerty Road). Head south on Haggerty Road approximately 1 mile. The Northville Health Center is on the east side at the corner of Haggerty and Seven Mile. Free surface parking is available directly next to the building.",
   mapUrl:"https://maps.google.com/?q=39901+Traditions+Dr,+Northville,+MI+48168"},
  {id:"ypsilanti",title:"Ypsilanti Health Center",tagline:"A cutting-edge health center bringing advanced care to downtown Ypsilanti.",
   address:"300 W. Michigan Ave., Ypsilanti, MI 48197",
   phone:"(734) 936-7030",
   hours:"Select days — call for current schedule",
   overview:"The new Ypsilanti Health Center is a state-of-the-art, nearly 50,000 square-foot facility in the heart of downtown Ypsilanti, located immediately next to the Ypsilanti Transit Center. More than three times the size of the former location, it offers expanded specialty care — including urology — alongside primary care, imaging, and laboratory services. The center is a key part of Michigan Medicine's strategy to improve health equity and access in the Ypsilanti community.",
   services:["General urology consultations","Community urology services","BPH and prostate screening","Hematuria evaluation","Post-surgical follow-up","On-site lab and imaging"],
   directions:"Located at 300 W. Michigan Avenue in downtown Ypsilanti. Free parking is available in the parking structure at 300 Pearl St., between N. Adams St. and N. Hamilton St. Park on Level 1 or 2 and follow signs into the Health Center. Accessible by bus — exit at the Ypsilanti Transit Center stop on Pearl St.",
   mapUrl:"https://maps.google.com/?q=300+W+Michigan+Ave,+Ypsilanti,+MI+48197"},
  {id:"muskegon",title:"West Shore Urology — Muskegon",tagline:"Full-spectrum urological care serving West Michigan.",
   address:"1301 Mercy Dr., Muskegon, MI 49444",
   phone:"(866) 876-6424",
   hours:"Monday–Friday — call for current schedule",
   overview:"West Shore Urology is Michigan Medicine's community urology practice serving West Michigan from its location on the Mercy Health campus in Muskegon. The clinic provides comprehensive adult and pediatric urology services, including urologic oncology, kidney stone management, incontinence treatment, men's health, and sexual medicine. The team includes multiple fellowship-trained urologists and advanced practice providers who bring Michigan Medicine expertise to the lakeshore community. Surgeries are performed at nearby Muskegon Surgery Center and Mercy Health Muskegon.",
   services:["Urologic oncology evaluation and treatment","Kidney stone management","Male and female incontinence","Men's health and sexual medicine","Vasectomy","Pediatric urology","BPH and prostate screening","General urology consultations"],
   directions:"Located on the Mercy Health campus at 1301 Mercy Drive in Muskegon. From US-31, take the Sherman Blvd exit and head east. Turn right on Mercy Drive. The building is on the left. Free surface parking is available.",
   mapUrl:"https://maps.google.com/?q=1301+Mercy+Dr,+Muskegon,+MI+49444"},
  {id:"troy",title:"Troy — Coming 2027",tagline:"Expanding Michigan Medicine urology access to Oakland County.",
   address:"Troy, MI — Location details forthcoming",
   phone:"(734) 936-7030",
   hours:"Opening 2027",
   overview:"Michigan Medicine is expanding its urology presence into Oakland County with a new clinic in Troy, Michigan, planned to open in 2027. This expansion reflects the department's commitment to bringing world-class urological care closer to where patients live and work, reducing travel time for the many patients in northern and eastern metro Detroit who currently travel to Ann Arbor for specialized services.",
   services:["Services to be announced — expected to include general urology, BPH, prostate cancer screening, and select specialty services"],
   directions:"Exact location and driving directions will be published as the opening date approaches. Sign up for updates by contacting (734) 936-7030.",
   mapUrl:"https://maps.google.com/?q=Troy,+MI"}
];
